[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wagtail-bakery"
version = "0.9.0"
description = "A set of helpers for baking your Django Wagtail site out as flat files."
readme = "README.md"
authors = [
    { name = "Wagtail Nest team", email = "hello@wagtail.org" },
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Wagtail",
    "Framework :: Wagtail :: 7",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "django-bakery~=0.13.5",
    "wagtail>=7.0",
]

[project.optional-dependencies]
test = [
    "coverage[toml]>=7.13.5,<8.0",
    "factory-boy",
    "flake8",
    "isort",
    "pytest-cov",
    "pytest-django",
    "pytest",
]

[project.urls]
Changelog = "https://github.com/wagtail-nest/wagtail-bakery/blob/main/CHANGELOG.md"
Homepage = "https://github.com/wagtail-nest/wagtail-bakery/"
"Issue tracker" = "https://github.com/wagtail-nest/wagtail-bakery/issues/"
Source = "https://github.com/wagtail-nest/wagtail-bakery/"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.isort]
line_length = 100
multi_line_output = 4
known_third_party = ["bakery", "django", "factory", "pytest", "wagtail"]

[tool.coverage.run]
branch = true
source_pkgs = ["wagtailbakery"]
omit = ["tests/*"]

[tool.coverage.paths]
source = ["src/wagtailbakery"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc.)?abstractmethod",

    # Nor complain about type checking
    "if TYPE_CHECKING:",
]
