[tox]
requires =
    tox>=4.2
env_list =
    py{314, 313, 312}-django60-wagtail{74, 73}
    py{313, 312, 311, 310}-django52-wagtail{74, 73, 70}
    wagtailmain

[testenv]
deps =
    django52: django<5.3,>=5.2
    django60: django<6.1,>=6
    wagtail70: wagtail<7.1,>=7
    wagtail73: wagtail>=7.3,<7.4  # Current LTS
    wagtail74: wagtail<7.5,>=7.4rc1
extras =
    test
set_env =
    COVERAGE_CORE = sysmon
    COVERAGE_FILE = .coverage.{envname}
commands =
    pytest --cov=wagtailbakery {posargs}

[testenv:wagtailmain]
deps =
    django<6.1,>=6
    https: //github.com/wagtail/wagtail/archive/refs/heads/main.zip
extras =
    test
set_env =
    COVERAGE_CORE = sysmon
    COVERAGE_FILE = .coverage.{envname}
commands =
    pytest --cov=wagtailbakery {posargs}
