[tox]
requires =
    tox>=4.2
env_list =
    py{315, 314, 313, 312}-django{61, 60}-wagtail74
    py{313, 312, 311, 310}-django52-wagtail{74, 70}
    future

[testenv]
deps =
    git+https://github.com/encode/django-rest-framework.git # Remove when DRF 3.18 is released with Django 6.1 support
    django52: django<5.3,>=5.2
    django60: django<6.1,>=6
    django61: django<6.2,>=6.1rc1
    wagtail70: wagtail<7.1,>=7 # Old LTS
    wagtail74: wagtail<7.5,>=7.4 # Current LTS
extras =
    test
set_env =
    COVERAGE_FILE = .coverage.{envname}
commands =
    pytest --cov=wagtailbakery {posargs}

[testenv:future]
description = Test against the main branch of Wagtail and Django
deps =
    future: https://github.com/django/django/archive/refs/heads/main.zip
    future: https://github.com/wagtail/wagtail/archive/refs/heads/main.zip
extras =
    test
set_env =
    COVERAGE_FILE = .coverage.{envname}
commands =
    pytest --cov=wagtailbakery {posargs}
