[tox]
# Necessary because we are using pyproject.toml
isolated_build = true
envlist=
  # Django 5.2, supported Wagtail versions (LTS + latest)
  py{310,311,312,313}-django52-wagtail{70,73,74}
  # Django 6.0, supported Wagtail versions (Django 6.0 support was added in Wagtail 7.3)
  py{312,313,314}-django60-wagtail{73,74}
  # Wagtail main latest compatible version
  wagtailmain

[testenv]
commands=pytest --cov=wagtailbakery {posargs}
setenv=
  COVERAGE_FILE=.coverage.{envname}
  COVERAGE_CORE=sysmon
deps=
  django52: django>=5.2,<5.3
  django60: django>=6.0,<6.1
  wagtail70: wagtail>=7.0,<7.1
  wagtail73: wagtail>=7.3,<7.4  # Current LTS
  wagtail74: wagtail>=7.4rc1,<7.5
extras=test

[testenv:wagtailmain]
commands=pytest --cov=wagtailbakery {posargs}
setenv=
  COVERAGE_FILE=.coverage.{envname}
  COVERAGE_CORE=sysmon
deps=
  django>=6.0,<6.1
  https://github.com/wagtail/wagtail/archive/refs/heads/main.zip
extras=test
