name: Wagtail Bakery CI

on:
  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linting
          - python: 3.8
            toxenv: flake8
            experimental: false
          - python: 3.8
            toxenv: isort
            experimental: false

          # All supported Django/Wagtail combinations with the latest supported Python version
          # Wagtail 2.11 - latest supported Python
          - python: 3.8
            toxenv: py38-django22-wagtail211
            experimental: false
          - python: 3.8
            toxenv: py38-django30-wagtail211
            experimental: false
          - python: 3.8
            toxenv: py38-django31-wagtail211
            experimental: false
          # Wagtail 2.13 - latest supported Python
          - python: 3.9
            toxenv: py39-django22-wagtail213
            experimental: false
          - python: 3.9
            toxenv: py39-django30-wagtail213
            experimental: false
          - python: 3.9
            toxenv: py39-django31-wagtail213
            experimental: false
          - python: 3.9
            toxenv: py39-django32-wagtail213
            experimental: false
          # The latest supported Django/Wagtail combination for the remaining Python versions
          - python: 3.6
            toxenv: py36-django32-wagtail213
            experimental: false
          - python: 3.7
            toxenv: py37-django32-wagtail213
            experimental: false
          - python: 3.8
            toxenv: py38-django32-wagtail213
            experimental: false
          # Future Wagtail release from main branch (allowed to fail)
          - python: 3.9
            toxenv: py39-django32-wagtailmain
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install coveralls tox
      - name: Test
        run: |
          tox
          coveralls
        env:
          TOXENV: ${{ matrix.toxenv }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
